# Use root/example as user/password credentials
version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongodb-express:
    image: mongo-express
    container_name: mongodb-web
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      # ME_CONFIG_MONGODB_URL: mongodb://admin:P@ssw0rd@mongodb:27017/
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
networks:
  default:
    external:
      name: dev