FROM alpine:latest
LABEL maintainer="YJ Tech frank.hsu@yjtech.com.tw"
RUN apk add --update --no-cache openssh && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    adduser -h /home/yj -s /bin/sh -D yj && \
    echo -n 'yj:P@ssw0rd' | chpasswd
ENTRYPOINT ["/entrypoint.sh"]
EXPOSE 22
COPY entrypoint.sh /