version: "3.7"
services:
  registry:
    container_name: registry
    image: registry:2.7
    hostname: registry.localhost.com
    ports:
      - 5000:5000
    environment:
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/localhost.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/localhost.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./vol/data:/var/lib/registry
      - ../self_certificates:/certs
      - ./vol/auth:/auth
      - ./vol/config:/etc/docker/registry
  ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui:latest
    ports:
      - 5555:80
    environment:
      REGISTRY_TITLE: Private Docker Registry
      NGINX_PROXY_PASS_URL: http://registry.localhost.com:5000
      SINGLE_REGISTRY: true
      DELETE_IMAGES: true
    depends_on:
        - registry
networks:
  default:
    external:
      name: dev