version: "3.7"
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
networks:
  default:
    external:
      name: dev

# Port	Protocol	Component	Function
# 6831	UDP	      agent	accept jaeger.thrift over Thrift-compact protocol (used by most SDKs)
# 6832	UDP	      agent	accept jaeger.thrift over Thrift-binary protocol (used by Node.js SDK)
# 5775	UDP	      agent	(deprecated) accept zipkin.thrift over compact Thrift protocol (used by legacy clients only)
# 5778	HTTP	    agent	serve configs (sampling, etc.)
# 16686	HTTP	    query	serve frontend
# 4317	HTTP	    collector	accept OpenTelemetry Protocol (OTLP) over gRPC, if enabled
# 4318	HTTP	    collector	accept OpenTelemetry Protocol (OTLP) over HTTP, if enabled
# 14268	HTTP	    collector	accept jaeger.thrift directly from clients
# 14250	HTTP	    collector	accept model.proto
# 9411	HTTP	    collector	Zipkin compatible endpoint (optional)