version: "3"
services:
  mysql:
    container_name: mysql
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_ROOT_HOST=%
      - MYSQL_PASSWORD_HOST=%
    volumes:
      - ../vol/mysql/mysql/data:/var/lib/mysql
      - ../vol/mysql/mysql/conf:/etc/mysql/conf.d
    ports:
      - 3306:3306
networks:
  default:
    external:
      name: dev