version: "3.7"
services:
  web:
    container_name: gitlab
    image: 'gitlab/gitlab-ee:latest'
    hostname: gitlab.localhost.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.localhost.com'
    ports:
      - 8081:80
      - 8433:443
      - 8022:22
    volumes:
      - ./vol/config:/etc/gitlab
      - ./vol/logs:/var/log/gitlab
      - ./vol/data:/var/opt/gitlab
    shm_size: '256m'
  runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    ports:
      - 8093:8093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vol/gitlab-runner/config:/etc/gitlab-runner
networks:
  default:
    external:
      name: dev