version: "3.7"
services:
    ngrok:
        image: ngrok/ngrok:latest
        restart: always
        container_name: ngrok
        command:
          - "start"
          - "--all"
          - "--config"
          - "/home/ngrok/.config/ngrok/ngrok.yml"
        volumes:
          - ./vol/ngrok.yml:/home/ngrok/.config/ngrok/ngrok.yml
        ports:
          - 4040:4040
