version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    privileged: true
    user: root
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./vol/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.11.2
    volumes:
      # - ./vol/logstash/config:/usr/share/logstash/config
      - ./logstash/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    links:
      - elasticsearch
  # filebeat:
  #   container_name: filebeat
  #   image: docker.elastic.co/beats/filebeat:7.11.2
  #   privileged: true
  #   user: root
  #   volumes:
  #     - ./filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - ./filebeat/conf/docker-entrypoint:/usr/local/bin/docker-entrypoint
  #     - ./vol/filebeat/log:/var/log
  #     - ./vol/filebeat/data:/usr/share/filebeat/data
  #   links:
  #     - logstash
  # apm:
  #   container_name: apm
  #   image: docker.elastic.co/apm/apm-server:7.11.2
  #   volumes:
  #     - ./apm/conf/apm-server.yml:/usr/share/apm-server/apm-server.yml
  #   links:
  #     - elasticsearch
  #   ports:
  #     - 8200:8200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.2
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    links:
      - elasticsearch
networks:
  default:
    external:
      name: dev
